REM file: implement.bat

REM -----------------------------------------------------------------------------
REM  Script to synthesize and implement the RTL provided for the clocking wizard
REM -----------------------------------------------------------------------------

REM Clean up the results directory
rmdir /S /Q results
mkdir results

REM Copy unisim_comp.v file to results directory
copy %XILINX%\verilog\src\iSE\unisim_comp.v .\results\

REM Synthesize the Verilog Wrapper Files
echo 'Synthesizing System Monitor Wizard design with XST'
xst -ifn xst.scr
copy TemperatureMonitor_exdes.ngc results\

REM  Copy the constraints files generated by Coregen
REM echo 'Copying files from constraints directory to results directory'
REM copy ..\TemperatureMonitor.ucf results\

cd results

echo 'Running ngdbuild'
ngdbuild TemperatureMonitor_exdes

echo 'Running map'
map -timing TemperatureMonitor_exdes -o mapped.ncd

echo 'Running par'
par -w mapped.ncd routed mapped.pcf

echo 'Running trce'
trce -e 10 routed -o routed mapped.pcf

echo 'Running design through bitgen'
bitgen -w routed

echo 'Running netgen to create gate level model for the System Monitor Wizard example design'
netgen -ofmt verilog -sim -tm TemperatureMonitor_exdes -w routed.ncd routed.v
cd ..

